import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  mkdtempSync,
  rmSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  chmodSync,
  existsSync,
} from 'node:fs';
import { execFileSync, spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { runInit } from '../src/cli/commands/init.js';
import { agentsSection, AGENTS_BEGIN, AGENTS_END } from '../src/agent/contract.js';

/**
 * What a teammate's agent meets after `git pull`: the section in AGENTS.md and
 * CLAUDE.md, the SessionStart hook, `.kadence/README.md`, and — for the person
 * who ran init — the message telling them what to commit.
 *
 * The teammate's machine may not have kadence at all. The hook and the section
 * both have to say so plainly, without reaching for the network.
 */

let dir: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'kadence-teammate-'));
  execFileSync('git', ['init', '-q'], { cwd: dir });
  execFileSync('git', ['config', 'user.email', 'tester@example.com'], { cwd: dir });
});
afterEach(() => rmSync(dir, { recursive: true, force: true }));

const settingsPath = (): string => join(dir, '.claude', 'settings.json');
function sessionStartEntries(): Array<Record<string, unknown>> {
  const settings = JSON.parse(readFileSync(settingsPath(), 'utf8')) as Record<string, unknown>;
  const groups = (settings['hooks'] as Record<string, unknown>)['SessionStart'] as Array<
    Record<string, unknown>
  >;
  return groups.flatMap((g) => g['hooks'] as Array<Record<string, unknown>>);
}
function installedHookCommand(): string {
  runInit(dir, 'dev', { hooks: true });
  const entries = sessionStartEntries();
  expect(entries).toHaveLength(1);
  return entries[0]!['command'] as string;
}

describe('T106 — the instruction-file section teaches writes', () => {
  const section = agentsSection('9.9.9');

  it('lists claim, note and decision add beside the read commands', () => {
    expect(section).toContain('kadence task claim');
    expect(section).toContain('kadence note "');
    expect(section).toMatch(/kadence decision add "[^"]*" --why "/);
    expect(section).toContain('kadence prime');
    expect(section).toContain('kadence decision list --json');
  });

  it('says in one line what to do when kadence is not on PATH, without assuming network', () => {
    const lines = section.split('\n').filter((l) => l.includes('npm install -g kadence'));
    expect(lines).toHaveLength(1);
    expect(lines[0]).toMatch(/not on PATH/);
    expect(lines[0]).toMatch(/human/);
  });

  it('stays within 25 lines and 2 KB — it is loaded into every session', () => {
    expect(section.split('\n').length).toBeLessThanOrEqual(25);
    expect(Buffer.byteLength(section, 'utf8')).toBeLessThanOrEqual(2048);
  });

  it('refreshes an older section written by a previous version', () => {
    const old =
      '# Our rules\n\nBe kind.\n\n' +
      `${AGENTS_BEGIN}\n<!-- generated by kadence 0.4.1 — refresh with \`kadence init\` -->\n` +
      '## Project tasks — kadence\n\n    kadence board --json\n' +
      `${AGENTS_END}\n\n## After\n`;
    writeFileSync(join(dir, 'AGENTS.md'), old, 'utf8');
    writeFileSync(join(dir, 'CLAUDE.md'), old, 'utf8');

    runInit(dir, '0.5.0');

    for (const file of ['AGENTS.md', 'CLAUDE.md']) {
      const text = readFileSync(join(dir, file), 'utf8');
      expect(text, file).toContain('kadence task claim');
      expect(text, file).not.toContain('kadence 0.4.1');
      expect(text, file).toContain('Be kind.');
      expect(text, file).toContain('## After');
      expect(text.split(AGENTS_BEGIN).length - 1, file).toBe(1);
    }
  });
});

describe('T107 — the SessionStart hook survives a machine without kadence', () => {
  it('keeps the startup matcher and the 60 s timeout', () => {
    runInit(dir, 'dev', { hooks: true });
    const settings = JSON.parse(readFileSync(settingsPath(), 'utf8')) as Record<string, unknown>;
    const group = ((settings['hooks'] as Record<string, unknown>)['SessionStart'] as Array<
      Record<string, unknown>
    >)[0]!;
    expect(group['matcher']).toBe('startup');
    expect((group['hooks'] as Array<Record<string, unknown>>)[0]!['timeout']).toBe(60);
  });

  it('never reaches for npx or the network', () => {
    expect(installedHookCommand()).not.toMatch(/npx|curl|wget/);
  });

  it('without kadence on PATH, prints an install hint for the agent and exits 0', () => {
    const command = installedHookCommand();
    const emptyBin = join(dir, 'empty-bin');
    mkdirSync(emptyBin);
    // /bin and /usr/bin for `sh` builtins' neighbours; neither holds kadence.
    const r = spawnSync('/bin/sh', ['-c', command], {
      cwd: dir,
      env: { PATH: `${emptyBin}:/usr/bin:/bin` },
      encoding: 'utf8',
    });
    expect(r.status).toBe(0);
    expect(r.stdout).toContain('npm install -g kadence');
    expect(r.stdout).toContain('.kadence/');
    expect(r.stdout.trim().split('\n')).toHaveLength(1);
  });

  it('with kadence on PATH, runs kadence prime', () => {
    const command = installedHookCommand();
    const bin = join(dir, 'fake-bin');
    mkdirSync(bin);
    const record = join(dir, 'called-with');
    const fake = join(bin, 'kadence');
    writeFileSync(fake, `#!/bin/sh\necho "$@" > '${record}'\necho primed\n`, 'utf8');
    chmodSync(fake, 0o755);

    const r = spawnSync('/bin/sh', ['-c', command], {
      cwd: dir,
      env: { PATH: `${bin}:/usr/bin:/bin` },
      encoding: 'utf8',
    });
    expect(r.status).toBe(0);
    expect(r.stdout).toContain('primed');
    expect(r.stdout).not.toContain('npm install');
    expect(existsSync(record)).toBe(true);
    expect(readFileSync(record, 'utf8').trim()).toBe('prime');
  });

  it('replaces the old `kadence prime` hook in place instead of adding a second', () => {
    mkdirSync(join(dir, '.claude'), { recursive: true });
    writeFileSync(
      settingsPath(),
      JSON.stringify({
        hooks: {
          SessionStart: [
            {
              matcher: 'startup',
              hooks: [
                { type: 'command', command: 'greet.sh' },
                { type: 'command', command: 'kadence prime', timeout: 60 },
                { type: 'command', command: 'after.sh' },
              ],
            },
          ],
        },
      }),
      'utf8',
    );

    runInit(dir, 'dev', { hooks: true });
    runInit(dir, 'dev', { hooks: true });

    const commands = sessionStartEntries().map((e) => e['command'] as string);
    expect(commands).toHaveLength(3);
    expect(commands[0]).toBe('greet.sh');
    expect(commands[2]).toBe('after.sh');
    expect(commands[1]).not.toBe('kadence prime');
    expect(commands[1]).toContain('command -v kadence');
  });
});

describe('T108 — .kadence/README.md', () => {
  const readme = (): string => readFileSync(join(dir, '.kadence', 'README.md'), 'utf8');

  it('lists decision list and decision add among the top commands, not sprint status', () => {
    runInit(dir);
    const commands = readme().split('## Commands')[1]!.split('\n## ')[0]!;
    expect(commands).toContain('kadence decision list --json');
    expect(commands).toContain('kadence decision add');
    expect(commands).toContain('kadence note');
    expect(commands).not.toContain('sprint status --json');
  });

  it('explains how to add a teammate', () => {
    runInit(dir);
    const section = readme().split('## Adding a teammate')[1];
    expect(section).toBeDefined();
    expect(section).toContain('npm install -g kadence');
    expect(section).toContain('git pull');
    expect(section).toContain('user.email');
    expect(section).toContain('KADENCE_SOURCE=agent');
    expect(section).toContain('task show');
  });

  it('is still never overwritten once it exists', () => {
    mkdirSync(join(dir, '.kadence'), { recursive: true });
    writeFileSync(join(dir, '.kadence', 'README.md'), 'our own rules\n', 'utf8');
    runInit(dir);
    expect(readme()).toBe('our own rules\n');
  });
});

describe('T109 — what init tells the person who ran it', () => {
  it('suggests a first task and a first decision', () => {
    const r = runInit(dir);
    expect(r.message).toContain('kadence task add "first task"');
    expect(r.message).toMatch(/kadence decision add "[^"]*" --why "/);
  });

  it('names what to commit so a teammate\'s agent finds it, and does not commit', () => {
    const r = runInit(dir);
    expect(r.message).toContain('.kadence/');
    expect(r.message).toContain('AGENTS.md');
    expect(r.message).toContain('CLAUDE.md');
    expect(r.message).not.toContain('.claude/settings.json');
    expect(r.message).toMatch(/not committed — that call is yours/);
  });

  it('adds .claude/settings.json to the list when --hooks installed the hook', () => {
    const r = runInit(dir, 'dev', { hooks: true });
    expect(r.message).toContain('.claude/settings.json');
  });

  it('mentions --hooks when .claude/ exists and no hook is installed', () => {
    mkdirSync(join(dir, '.claude'));
    const r = runInit(dir);
    expect(r.message).toContain('kadence init --hooks adds prime at session start');
  });

  it('does not mention --hooks without a .claude/ folder', () => {
    const r = runInit(dir);
    expect(r.message).not.toContain('kadence init --hooks');
  });

  it('does not mention --hooks when the old hook is already installed', () => {
    mkdirSync(join(dir, '.claude'));
    writeFileSync(
      settingsPath(),
      JSON.stringify({
        hooks: {
          SessionStart: [
            { matcher: 'startup', hooks: [{ type: 'command', command: 'kadence prime' }] },
          ],
        },
      }),
      'utf8',
    );
    const r = runInit(dir);
    expect(r.message).not.toContain('kadence init --hooks adds');
  });
});
