/**
 * Provenance for the files we write into someone else's repository.
 *
 * A context file with no marker rots silently: a year on nobody knows whether it
 * is current or what put it there. Carries the version and not a date on
 * purpose — a date would rewrite the file on every new day and fill diffs with
 * noise, while the version changes exactly when the content might have
 * (docs/research/context-handoff-2026-09.md §1.5).
 */
function provenance(version: string): string {
  return `<!-- generated by kadence ${version} — refresh with \`kadence init\` -->`;
}

/** A document the agent reads as a plain file — no MCP, no network, no token. */
export function agentReadme(version: string): string {
  return `${provenance(version)}
# kadence — for AI agents

This project's tasks live here as plain files. Read them directly, or through
the CLI. No server required.

## Commands

    kadence prime                        start here — the live state, in 40 lines
    kadence ready --json                 what can be started right now
    kadence task claim KAD-42           take it; no argument takes the top of ready
    kadence board --json                 the whole board
    kadence task list --json             all tasks
    kadence task show KAD-42 --json     one task with its history
    kadence task add "title" -d "..." --type bug --estimate 3
    kadence task move KAD-42 in_progress
    kadence task assign KAD-42 you@example.com
    kadence sprint status --json         current sprint progress
    kadence note "text" --task KAD-42   something learned; a choice is a decision

## JSON contract

Every \`--json\` response carries \`schema: "kadence/v1"\`. stdout holds JSON and
nothing else; warnings go to stderr. Exit codes: 0 success, 1 runtime error,
2 bad arguments.

The contract itself is machine-readable — read it instead of guessing:

    kadence schema --json

It lists every command, the fields you can rely on, and every error code. It
works outside a repository, so you can read it before \`init\`.

## When something fails

A failed \`--json\` call carries \`error.code\` — branch on that, not on the
sentence. Where the valid set is knowable it also carries \`allowed\`:

    { "ok": false,
      "error": { "code": "unknown_status", "received": "shipped",
                 "allowed": ["backlog", "in_progress", "done"],
                 "hint": "kadence board statuses --json" } }

Statuses are configured per project, so \`allowed\` is the only reliable source —
never assume the defaults. Retrying an identical command never helps: there is no
network and no lock, so the same input always fails the same way.

## Working as an agent

Set \`KADENCE_SOURCE=agent\` so events record your authorship. Without it an
event is marked as human — we do not guess.

## Why to ask rather than read the files

You cannot find a task by its label in the journal. \`KAD-3\` is derived while
folding and is never stored in an event, so \`grep -r "KAD-3" .kadence/events/\`
returns nothing. Folding the journal yourself is the only alternative to asking.

Asking is also cheaper, and stays cheap: \`task show --json\` is about 950 bytes
whether the project holds ten tasks or a thousand, while the journal behind it
grows past 500 KB.

\`board --json\` is the exception: it returns every task in full, which on a large
project is a lot of description you did not ask for. Narrow it:

    kadence board --json --fields label,status,assignee
    kadence task list --json --fields id,label,status

\`kadence schema --json\` lists every selectable field.

## Recording why

The journal holds what happened. \`decision\` holds why, which the code and
\`git log\` never carry:

    kadence decision add "Use ULIDs" --why "Clocks disagree between machines" \\
      --rejected "Auto-increment: collides across branches" --task KAD-1

\`--why\` is required: without it the record is a changelog line. \`--rejected\` is
what stops the next agent proposing the thing that was already turned down.

When a decision stops being true, do not edit it — supersede it:

    kadence decision add "Use signed tokens" --why "..." --supersedes DEC-1

One event writes both directions. \`decision list\` then returns only what is
still in force; pass \`--all\` when you need the history too. **Read the default,
not \`--all\`** — a reversed reason quoted as current is worse than no memory.

## Documents

\`kadence task doc KAD-1 docs/design.md\` links a document to a task, and
\`task show --json\` returns the links. kadence does not store the document: it
stays plain markdown in the repository. The link is the part git cannot express.

## What not to do

Do not hand-edit files under \`.kadence/events/\`: the journal is appended to,
never modified. To correct the state, add a new event through the CLI.
`;
}

export const AGENTS_BEGIN = '<!-- kadence:begin -->';
export const AGENTS_END = '<!-- kadence:end -->';

/** Section for the instruction files — short, since details live in .kadence/README.md. */
export function agentsSection(version: string): string {
  return `${AGENTS_BEGIN}
${provenance(version)}
## Project tasks — kadence

Tasks live in \`.kadence/\` as plain files. Read them directly or via the CLI:

    kadence prime                  start here: sprint, your work, what is ready
    kadence board --json --summary the board's state, without the history
    kadence board --json           the whole board, history included
    kadence task list --json       all tasks
    kadence task move KAD-1 done  change state

    kadence schema --json          the contract: commands, fields, error codes
    kadence decision list --json   why the current choices were made

\`--json\` responses carry \`schema: "kadence/v1"\`; stdout is JSON only. A failure
carries \`error.code\` and, where knowable, \`allowed\`.
When acting as an agent, set \`KADENCE_SOURCE=agent\`.

Details: \`.kadence/README.md\`
${AGENTS_END}`;
}

/**
 * Inserts or updates the kadence section, leaving the rest of the file intact.
 *
 * The boundaries are comments rather than a heading: a human can rename a
 * heading, and then a repeat init would create a duplicate.
 */
export function upsertAgentsSection(existing: string | null, version: string): string {
  const section = agentsSection(version);
  if (existing === null || existing.trim().length === 0) {
    return `${section}\n`;
  }

  const start = existing.indexOf(AGENTS_BEGIN);
  const end = existing.indexOf(AGENTS_END);

  if (start !== -1 && end !== -1 && end > start) {
    const before = existing.slice(0, start);
    const after = existing.slice(end + AGENTS_END.length);
    return `${before}${section}${after}`;
  }

  const sep = existing.endsWith('\n') ? '\n' : '\n\n';
  return `${existing}${sep}${section}\n`;
}

/**
 * The task fields `--fields` can select.
 *
 * Same order as `serializeTask` emits them, and published in the contract: an
 * agent that cannot see the list has to guess, and a guess costs it a round trip
 * (Probe C §4).
 */
export const TASK_FIELDS = [
  'id',
  'label',
  'title',
  'description',
  'type',
  'priority',
  'status',
  'labels',
  'assignee',
  'reporter',
  'sprint',
  'milestone',
  'loggedHours',
  'parent',
  'blockedBy',
  'due',
  'claimedBy',
  'contestedBy',
  'criteria',
  'openCriteria',
  'comments',
  'estimate',
  'history',
] as const;

/**
 * Every failure kadence can name.
 *
 * Agents branch on these, so the list is part of the --json contract: a code may
 * be added, never renamed or removed (ADR-009). `kadence schema --json`
 * publishes it, and a test asserts the two cannot drift.
 */
export const ERROR_CODES = [
  'not_a_repository',
  'not_initialised',
  'no_git_identity',
  'task_not_found',
  'sprint_not_found',
  'decision_not_found',
  'unknown_status',
  'unknown_type',
  'unknown_priority',
  'unknown_field',
  'invalid_argument',
  'template_not_found',
  'conflicting_state',
  'nothing_ready',
  'milestone_not_found',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

const ERROR_MEANINGS: Record<ErrorCode, string> = {
  not_a_repository: 'There is no git repository here. kadence stores its journal inside one.',
  not_initialised: 'The repository has no .kadence/ folder yet. Run `kadence init`.',
  no_git_identity: 'Git has no user.email, so an event would have no author.',
  task_not_found: 'No task carries that ULID or KAD-N label. Nothing was changed.',
  sprint_not_found: 'No sprint carries that name or id.',
  decision_not_found: 'No decision carries that ULID or DEC-N label.',
  unknown_status:
    'The status is not one of this project\u2019s columns. They are configurable, so read `allowed`.',
  unknown_type: 'The task type is not one of the four kadence defines.',
  unknown_priority: 'The priority is not one of the four kadence defines.',
  unknown_field: 'A name given to --fields is not a task field. Read `allowed`.',
  invalid_argument: 'An argument was missing or malformed; the command did nothing.',
  template_not_found: 'No template carries that name.',
  conflicting_state:
    'The arguments were understood, but the current state does not allow it \u2014 a closed sprint, or one already started.',
  milestone_not_found: 'No milestone carries that name, MS-N label or ULID.',
  nothing_ready:
    'Nothing can be started right now: the board is empty, or every open task is blocked or claimed by someone else. The message says which.',
};

/**
 * The machine-readable contract behind `schema: "kadence/v1"`.
 *
 * Deliberately narrower than the actual output. Every field named here is a
 * promise we keep; anything we emit but do not list may still change, which is
 * the only way to leave room to grow (Hyrum\u2019s Law cuts both ways).
 */
export function buildContract(version: string): Record<string, unknown> {
  return {
    version: 'kadence/v1',
    tool: { name: 'kadence', version },
    stability:
      'Additive only: fields and error codes may be added, never renamed or removed within kadence/v1.',
    exitCodes: {
      '0': 'success',
      '1': 'runtime error — the command understood you and could not comply',
      '2': 'bad arguments — nothing was attempted',
    },
    output: {
      stdout: 'With --json, JSON and nothing else.',
      stderr: 'Warnings and human messages, never part of the contract.',
    },
    env: {
      KADENCE_SOURCE:
        'Set to "agent" so events record agent authorship. Without it an event counts as human — we do not guess.',
      NO_COLOR: 'Any value disables colour.',
    },
    errors: ERROR_CODES.map((code) => ({ code, meaning: ERROR_MEANINGS[code] })),
    shapes: {
      task: {
        required: [
          'id',
          'label',
          'title',
          'status',
          'type',
          'priority',
          'estimate',
          'assignee',
          'blockedBy',
          'loggedHours',
          // Claim state is what a second agent branches on before starting
          // work, so it is a promise and not merely something we happen to
          // emit. `contestedBy` is always an array, empty when nobody else
          // claimed it — an agent should never have to test for null.
          'claimedBy',
          'contestedBy',
          // Promoted on 2026-09-11, once labels stopped being lossy (ADR-013).
          // A team's own vocabulary lives here and nothing else carries it, so
          // an agent that reads a task has to be able to rely on it.
          'labels',
        ],
        selectable: [...TASK_FIELDS],
        notes: {
          id: 'ULID. The identity of the task; KAD-N is a label derived while folding and is never stored.',
          history: 'Present in `task show` only — the events that produced this state.',
          required:
            'What a full response carries. With --fields you get exactly what you asked for and nothing else.',
        },
      },
      board: {
        required: ['schema', 'ok', 'columns'],
        notes: {
          columns:
            'With --summary each task carries only the state fields, never `history` or `comments`. The response without the flag is unchanged \u2014 the contract only ever gains.',
        },
      },
      ready: {
        required: ['label', 'title', 'priority', 'estimate', 'labels', 'claimedBy', 'contestedBy'],
        notes: {
          contestedBy:
            'Always an array. Non-empty means two people claimed the task and it is in this list on purpose — it needs a person, not a filter.',
          labels:
            'Always an array, empty when there are none. Free-form: kadence attaches no meaning to any label. A team that marks blast radius — impact-critical and the like — decides from this how carefully to work; the mapping from a label to how an agent behaves is the team\u2019s, never ours.',
          priority:
            'Urgency, from a fixed vocabulary: low, normal, high, urgent. Not blast radius \u2014 that is a label, and the two are different questions.',
        },
      },
      milestone: {
        required: ['label', 'name', 'due', 'status', 'doneTasks', 'totalTasks', 'donePoints', 'totalPoints'],
        notes: {
          label: 'MS-N, derived from ULID order during the fold, exactly like KAD-N. It can change when a branch merges.',
          donePoints: 'Progress is measured in points, the same unit as velocity and burndown.',
        },
      },
      criterion: {
        required: ['n', 'text', 'checked', 'checkedBy'],
        notes: {
          n: 'A position in the folded list, assigned like KAD-N and never stored. It can change when a branch merges.',
          checkedBy: 'Who checked it, or null. Cleared when it is unchecked.',
        },
      },
      branch: {
        required: ['name', 'base'],
        notes: {
          name: 'Present on a `task list --branch` response only. A task belongs to the branch when it was created there or any event about it arrived there; nothing is stored, the answer comes from git at read time.',
        },
      },
      note: {
        required: ['id', 'text', 'task', 'at', 'by', 'source'],
        notes: {
          task: 'The KAD-N label, or null. A note is not a decision: there is no `why` and no number.',
        },
      },
      flow: {
        required: [
          'schema', 'ok', 'report', 'window', 'started', 'unit', 'wip', 'finished',
          'perWeek', 'cycleTime', 'leadTime', 'responseTime', 'sle', 'aging', 'blocked', 'notes',
        ],
        notes: {
          cycleTime: 'null, or {n, p50, p85, p95} in calendar days. Percentiles only \u2014 there is no mean, on purpose.',
          started: 'The column work counts as started at. A cycle time quoted without it is a number about the default, not the team.',
          window: 'UTC dates, inclusive at both ends. `--since 1` is the current UTC day.',
        },
      },
      cfd: {
        required: ['schema', 'ok', 'report', 'window', 'statuses', 'days'],
        notes: {
          days: 'One row per day of the window, each with a count per column at the end of that UTC day. A move backwards subtracts.',
        },
      },
      attention: {
        required: ['schema', 'ok', 'report', 'threshold', 'started', 'asOf', 'rows', 'notes'],
        notes: {
          rows: 'One row per task, however many signals it carries. `signals[].kind` is one of stalled, unowned, stale_claim, dead_blocker.',
          threshold: 'Days of silence before work counts as stalled, and the age a claim must reach. From `--since`; the default is 7, not the 30 a window report uses.',
          asOf: 'The UTC day the question was asked. This report is the one answer that changes without the journal changing.',
        },
      },
      prime: {
        required: ['sprint', 'mine', 'mineTotal', 'ready', 'attention', 'attentionTotal', 'decisions', 'notes', 'commands'],
        notes: {
          mine: 'Capped; `mineTotal` is the real count.',
          ready: 'A count, not a list. `kadence ready --json` returns the list.',
          attention: 'Work in flight that nobody is moving, at most three, `attentionTotal` is the real count. Empty when there is nothing \u2014 and then the human output says nothing at all. `kadence report attention --json` returns the rest.',
        },
      },
      decision: {
        required: [
          'id', 'label', 'title', 'why', 'rejected', 'docs', 'supersedes', 'supersededBy',
          'source',
        ],
        notes: {
          why: 'The reason. Required when recording — a decision without one is a changelog line.',
          supersededBy:
            'Derived while folding from a later decision carrying `supersedes`. Both directions come from one write, so they cannot fall out of step.',
          docs: 'Repository-relative paths. kadence does not store the documents, only the link.',
          source:
            '"human" or "agent", from KADENCE_SOURCE at the time of writing. Never guessed: without the variable an event counts as human.',
          listing:
            '`decision list` hides superseded decisions unless --all is passed: a reversed reason presented as current is worse than no memory.',
        },
      },
      error: {
        required: ['code', 'message'],
        optional: ['received', 'allowed', 'hint'],
        notes: {
          allowed: 'Present when the valid set is knowable — statuses are project-configurable.',
          retryable: 'Deliberately absent: no network, no lock, so a retry always fails identically.',
        },
      },
    },
    commands: [
      { name: 'schema', summary: 'This contract. Works outside a repository.' },
      { name: 'init', summary: 'Create .kadence/ and the agent instruction files.' },
      {
        name: 'board',
        summary:
          'The whole board, grouped by column. Every task in full \u2014 pass --summary for the state without history and comments, which is what makes a large board big.',
        flags: ['--json', '--fields', '--summary'],
        json: true,
      },
      {
        name: 'prime',
        summary:
          'The session preamble: active sprint, your claimed work, how many tasks are ready, decisions in force, recent notes. Capped at 40 lines.',
        flags: ['--json'],
        json: true,
      },
      {
        name: 'ready',
        summary:
          'What can be started now: open, unblocked, not claimed by anyone else. Priority first, then age.',
        flags: ['--json', '--assignee', '--limit'],
        json: true,
      },
      {
        name: 'task claim',
        summary:
          'Take a task, or the top of `ready` with no argument. No lock: a second claim is recorded and reported as contested.',
        args: ['ref'],
        json: true,
      },
      { name: 'task release', summary: 'Give a claimed task back.', args: ['ref'], json: true },
      {
        name: 'task list',
        summary:
          'All tasks, filterable. `--branch` narrows to the work the current branch introduced, measured against `--base` (main by default).',
        flags: ['--json', '--fields', '--branch', '--base'],
        json: true,
      },
      {
        name: 'task show',
        summary: 'One task with its comments and full history.',
        args: ['ref'],
        json: true,
      },
      { name: 'task add', summary: 'Create a task.', args: ['title'], json: true },
      {
        name: 'task move',
        summary: 'Change status. Accepts several refs, all or nothing.',
        args: ['refs', 'status'],
        json: true,
      },
      { name: 'task assign', summary: 'Assign or unassign.', args: ['refs', 'who'], json: true },
      { name: 'task comment', summary: 'Append a comment.', args: ['ref', 'text'], json: true },
      {
        name: 'task edit',
        summary:
          'Change fields. Labels move as deltas: --add-label and --remove-label change one and leave the rest, --label makes the set exactly what you pass. Prefer the first two \u2014 a whole set passed from two branches is two people’s intent, and only the difference is recorded (ADR-013).',
        args: ['refs'],
        flags: ['--title', '--description', '--type', '--priority', '--due', '--estimate', '--label', '--add-label', '--remove-label', '--json'],
        json: true,
      },
      { name: 'task log', summary: 'Log hours.', args: ['refs', 'hours'], json: true },
      { name: 'task block', summary: 'Record a blocker.', args: ['ref', 'blocker'], json: true },
      {
        name: 'task ac',
        summary:
          'Acceptance criteria: `add <ref> "text"`, `check <ref> <n>`, `uncheck <ref> <n>`, `list <ref>`. The number is a position in the folded list, never stored. Moving to done with unchecked criteria warns and proceeds.',
        args: ['action', 'ref', 'value'],
        json: true,
      },
      {
        name: 'note',
        summary:
          'Record something learned that was never a choice. For a choice with a rejected alternative, use `decision add`.',
        args: ['text'],
        flags: ['--task', '--json'],
        json: true,
      },
      {
        name: 'note list',
        summary: 'Notes, newest first.',
        flags: ['--task', '--limit', '--json'],
        json: true,
      },
      {
        name: 'decision add',
        summary: 'Record why something was chosen, and what was turned down.',
        args: ['title'],
        flags: ['--why', '--rejected', '--task', '--supersedes', '--doc'],
        json: true,
      },
      {
        name: 'decision list',
        summary: 'Current decisions. Superseded ones need --all.',
        flags: ['--all', '--task'],
        json: true,
      },
      { name: 'decision show', summary: 'One decision in full.', args: ['ref'], json: true },
      {
        name: 'task doc',
        summary:
          'Link a document to a task; `task doc add <ref> <path>` creates it from a small template and links it in one call. The file stays plain markdown in the repo and is never overwritten.',
        args: ['ref', 'path'],
        json: true,
      },
      {
        name: 'report flow',
        summary:
          'WIP, throughput per week, cycle / lead / response time as p50 p85 p95 in calendar days, aging work against p85, created vs resolved, blocked days. Names the window and the started boundary it used.',
        flags: ['--since', '--json'],
        json: true,
      },
      {
        name: 'report cfd',
        summary: 'Cumulative flow: tasks per column at the end of each day in the window.',
        flags: ['--since', '--json'],
        json: true,
      },
      {
        name: 'report attention',
        summary:
          'Work past the started boundary that nobody is moving: stalled, unowned, held by a stale claim, or blocked by something already done. `--since` is days of silence, default 7.',
        flags: ['--since', '--json'],
        json: true,
      },
      {
        name: 'compact',
        summary:
          'Fold months older than --keep-months into one archive file each. Same events, faster cold start; an archived month is one file, so compact on one branch and merge before compacting on another.',
        flags: ['--keep-months', '--dry-run', '--json'],
        json: true,
      },
      {
        name: 'stats',
        summary:
          'Counts by status and assignee, open blockers, contested claims, and the velocity of the last three closed sprints.',
        flags: ['--json'],
        json: true,
      },
      {
        name: 'milestone list',
        summary:
          'Milestones with progress in points. Grouping by outcome, where an epic groups by structure and a sprint by time. Closed ones need --all.',
        flags: ['--all', '--json'],
        json: true,
      },
      {
        name: 'milestone create',
        summary: 'Create one. A task carries at most one milestone, as a field beside `sprint`.',
        args: ['name'],
        flags: ['--due', '--json'],
        json: true,
      },
      {
        name: 'milestone add',
        summary: 'Put a task in a milestone; it leaves the one it was in.',
        args: ['ref'],
        flags: ['--milestone', '--json'],
        json: true,
      },
      {
        name: 'milestone close',
        summary: 'Close it. A statement about the calendar, not about the work: open tasks stay open and are named.',
        args: ['ref'],
        json: true,
      },
      {
        name: 'board export',
        summary:
          'Write a snapshot: `--html` for one self-contained file that opens from disk, `--md` for a README or a pull request. No server and no network; nothing outlives the command.',
        flags: ['--html', '--md', '--readme', '--file', '--json'],
        json: true,
      },
      {
        name: 'board config',
        summary:
          'Read or set the columns, the started boundary and the definition of done. `--started` names the column cycle time and actual hours count from; `--dod` criteria are copied into each new task, never referenced.',
        flags: ['--statuses', '--started', '--dod', '--json'],
        json: true,
      },
      { name: 'sprint status', summary: 'Current sprint progress.', json: true },
      { name: 'sprint create', summary: 'Start a sprint.', args: ['name'], json: true },
      { name: 'sprint close', summary: 'Close it and report velocity.', json: true },
    ],
  };
}
