/**
 * Provenance for the files we write into someone else's repository.
 *
 * A context file with no marker rots silently: a year on nobody knows whether it
 * is current or what put it there. Carries the version and not a date on
 * purpose — a date would rewrite the file on every new day and fill diffs with
 * noise, while the version changes exactly when the content might have
 * (docs/research/context-handoff-2026-09.md §1.5).
 */
function provenance(version: string): string {
  return `<!-- generated by kadence ${version} — refresh with \`kadence init\` -->`;
}

/** A document the agent reads as a plain file — no MCP, no network, no token. */
export function agentReadme(version: string): string {
  return `${provenance(version)}
# kadence — for AI agents

This project's tasks live here as plain files. Read them directly, or through
the CLI. No server required.

## Commands

    kadence board --json                 the whole board
    kadence task list --json             all tasks
    kadence task show KAD-42 --json     one task with its history
    kadence task add "title" -d "..." --type bug --estimate 3
    kadence task move KAD-42 in_progress
    kadence task assign KAD-42 you@example.com
    kadence sprint status --json         current sprint progress

## JSON contract

Every \`--json\` response carries \`schema: "kadence/v1"\`. stdout holds JSON and
nothing else; warnings go to stderr. Exit codes: 0 success, 1 runtime error,
2 bad arguments.

The contract itself is machine-readable — read it instead of guessing:

    kadence schema --json

It lists every command, the fields you can rely on, and every error code. It
works outside a repository, so you can read it before \`init\`.

## When something fails

A failed \`--json\` call carries \`error.code\` — branch on that, not on the
sentence. Where the valid set is knowable it also carries \`allowed\`:

    { "ok": false,
      "error": { "code": "unknown_status", "received": "shipped",
                 "allowed": ["backlog", "in_progress", "done"],
                 "hint": "kadence board statuses --json" } }

Statuses are configured per project, so \`allowed\` is the only reliable source —
never assume the defaults. Retrying an identical command never helps: there is no
network and no lock, so the same input always fails the same way.

## Working as an agent

Set \`KADENCE_SOURCE=agent\` so events record your authorship. Without it an
event is marked as human — we do not guess.

## Why to ask rather than read the files

You cannot find a task by its label in the journal. \`KAD-3\` is derived while
folding and is never stored in an event, so \`grep -r "KAD-3" .kadence/events/\`
returns nothing. Folding the journal yourself is the only alternative to asking.

Asking is also cheaper, and stays cheap: \`task show --json\` is about 950 bytes
whether the project holds ten tasks or a thousand, while the journal behind it
grows past 500 KB.

\`board --json\` is the exception: it returns every task in full, which on a large
project is a lot of description you did not ask for. Narrow it:

    kadence board --json --fields label,status,assignee
    kadence task list --json --fields id,label,status

\`kadence schema --json\` lists every selectable field.

## Recording why

The journal holds what happened. \`decision\` holds why, which the code and
\`git log\` never carry:

    kadence decision add "Use ULIDs" --why "Clocks disagree between machines" \\
      --rejected "Auto-increment: collides across branches" --task KAD-1

\`--why\` is required: without it the record is a changelog line. \`--rejected\` is
what stops the next agent proposing the thing that was already turned down.

When a decision stops being true, do not edit it — supersede it:

    kadence decision add "Use signed tokens" --why "..." --supersedes DEC-1

One event writes both directions. \`decision list\` then returns only what is
still in force; pass \`--all\` when you need the history too. **Read the default,
not \`--all\`** — a reversed reason quoted as current is worse than no memory.

## Documents

\`kadence task doc KAD-1 docs/design.md\` links a document to a task, and
\`task show --json\` returns the links. kadence does not store the document: it
stays plain markdown in the repository. The link is the part git cannot express.

## What not to do

Do not hand-edit files under \`.kadence/events/\`: the journal is appended to,
never modified. To correct the state, add a new event through the CLI.
`;
}

export const AGENTS_BEGIN = '<!-- kadence:begin -->';
export const AGENTS_END = '<!-- kadence:end -->';

/** Section for the instruction files — short, since details live in .kadence/README.md. */
export function agentsSection(version: string): string {
  return `${AGENTS_BEGIN}
${provenance(version)}
## Project tasks — kadence

Tasks live in \`.kadence/\` as plain files. Read them directly or via the CLI:

    kadence board --json           the whole board
    kadence task list --json       all tasks
    kadence task move KAD-1 done  change state

    kadence schema --json          the contract: commands, fields, error codes
    kadence decision list --json   why the current choices were made

\`--json\` responses carry \`schema: "kadence/v1"\`; stdout is JSON only. A failure
carries \`error.code\` and, where knowable, \`allowed\`.
When acting as an agent, set \`KADENCE_SOURCE=agent\`.

Details: \`.kadence/README.md\`
${AGENTS_END}`;
}

/**
 * Inserts or updates the kadence section, leaving the rest of the file intact.
 *
 * The boundaries are comments rather than a heading: a human can rename a
 * heading, and then a repeat init would create a duplicate.
 */
export function upsertAgentsSection(existing: string | null, version: string): string {
  const section = agentsSection(version);
  if (existing === null || existing.trim().length === 0) {
    return `${section}\n`;
  }

  const start = existing.indexOf(AGENTS_BEGIN);
  const end = existing.indexOf(AGENTS_END);

  if (start !== -1 && end !== -1 && end > start) {
    const before = existing.slice(0, start);
    const after = existing.slice(end + AGENTS_END.length);
    return `${before}${section}${after}`;
  }

  const sep = existing.endsWith('\n') ? '\n' : '\n\n';
  return `${existing}${sep}${section}\n`;
}

/**
 * The task fields `--fields` can select.
 *
 * Same order as `serializeTask` emits them, and published in the contract: an
 * agent that cannot see the list has to guess, and a guess costs it a round trip
 * (Probe C §4).
 */
export const TASK_FIELDS = [
  'id',
  'label',
  'title',
  'description',
  'type',
  'priority',
  'status',
  'labels',
  'assignee',
  'reporter',
  'sprint',
  'loggedHours',
  'parent',
  'blockedBy',
  'due',
  'comments',
  'estimate',
  'history',
] as const;

/**
 * Every failure kadence can name.
 *
 * Agents branch on these, so the list is part of the --json contract: a code may
 * be added, never renamed or removed (ADR-009). `kadence schema --json`
 * publishes it, and a test asserts the two cannot drift.
 */
export const ERROR_CODES = [
  'not_a_repository',
  'not_initialised',
  'no_git_identity',
  'task_not_found',
  'sprint_not_found',
  'decision_not_found',
  'unknown_status',
  'unknown_type',
  'unknown_priority',
  'unknown_field',
  'invalid_argument',
  'template_not_found',
  'conflicting_state',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

const ERROR_MEANINGS: Record<ErrorCode, string> = {
  not_a_repository: 'There is no git repository here. kadence stores its journal inside one.',
  not_initialised: 'The repository has no .kadence/ folder yet. Run `kadence init`.',
  no_git_identity: 'Git has no user.email, so an event would have no author.',
  task_not_found: 'No task carries that ULID or KAD-N label. Nothing was changed.',
  sprint_not_found: 'No sprint carries that name or id.',
  decision_not_found: 'No decision carries that ULID or DEC-N label.',
  unknown_status:
    'The status is not one of this project\u2019s columns. They are configurable, so read `allowed`.',
  unknown_type: 'The task type is not one of the four kadence defines.',
  unknown_priority: 'The priority is not one of the four kadence defines.',
  unknown_field: 'A name given to --fields is not a task field. Read `allowed`.',
  invalid_argument: 'An argument was missing or malformed; the command did nothing.',
  template_not_found: 'No template carries that name.',
  conflicting_state:
    'The arguments were understood, but the current state does not allow it \u2014 a closed sprint, or one already started.',
};

/**
 * The machine-readable contract behind `schema: "kadence/v1"`.
 *
 * Deliberately narrower than the actual output. Every field named here is a
 * promise we keep; anything we emit but do not list may still change, which is
 * the only way to leave room to grow (Hyrum\u2019s Law cuts both ways).
 */
export function buildContract(version: string): Record<string, unknown> {
  return {
    version: 'kadence/v1',
    tool: { name: 'kadence', version },
    stability:
      'Additive only: fields and error codes may be added, never renamed or removed within kadence/v1.',
    exitCodes: {
      '0': 'success',
      '1': 'runtime error — the command understood you and could not comply',
      '2': 'bad arguments — nothing was attempted',
    },
    output: {
      stdout: 'With --json, JSON and nothing else.',
      stderr: 'Warnings and human messages, never part of the contract.',
    },
    env: {
      KADENCE_SOURCE:
        'Set to "agent" so events record agent authorship. Without it an event counts as human — we do not guess.',
      NO_COLOR: 'Any value disables colour.',
    },
    errors: ERROR_CODES.map((code) => ({ code, meaning: ERROR_MEANINGS[code] })),
    shapes: {
      task: {
        required: [
          'id',
          'label',
          'title',
          'status',
          'type',
          'priority',
          'estimate',
          'assignee',
          'blockedBy',
          'loggedHours',
        ],
        selectable: [...TASK_FIELDS],
        notes: {
          id: 'ULID. The identity of the task; KAD-N is a label derived while folding and is never stored.',
          history: 'Present in `task show` only — the events that produced this state.',
          required:
            'What a full response carries. With --fields you get exactly what you asked for and nothing else.',
        },
      },
      board: { required: ['schema', 'ok', 'columns'] },
      decision: {
        required: [
          'id', 'label', 'title', 'why', 'rejected', 'docs', 'supersedes', 'supersededBy',
          'source',
        ],
        notes: {
          why: 'The reason. Required when recording — a decision without one is a changelog line.',
          supersededBy:
            'Derived while folding from a later decision carrying `supersedes`. Both directions come from one write, so they cannot fall out of step.',
          docs: 'Repository-relative paths. kadence does not store the documents, only the link.',
          source:
            '"human" or "agent", from KADENCE_SOURCE at the time of writing. Never guessed: without the variable an event counts as human.',
          listing:
            '`decision list` hides superseded decisions unless --all is passed: a reversed reason presented as current is worse than no memory.',
        },
      },
      error: {
        required: ['code', 'message'],
        optional: ['received', 'allowed', 'hint'],
        notes: {
          allowed: 'Present when the valid set is knowable — statuses are project-configurable.',
          retryable: 'Deliberately absent: no network, no lock, so a retry always fails identically.',
        },
      },
    },
    commands: [
      { name: 'schema', summary: 'This contract. Works outside a repository.' },
      { name: 'init', summary: 'Create .kadence/ and the agent instruction files.' },
      {
        name: 'board',
        summary:
          'The whole board, grouped by column. Every task in full — pass --fields on a large project.',
        flags: ['--json', '--fields'],
        json: true,
      },
      {
        name: 'task list',
        summary: 'All tasks, filterable.',
        flags: ['--json', '--fields'],
        json: true,
      },
      {
        name: 'task show',
        summary: 'One task with its comments and full history.',
        args: ['ref'],
        json: true,
      },
      { name: 'task add', summary: 'Create a task.', args: ['title'], json: true },
      {
        name: 'task move',
        summary: 'Change status. Accepts several refs, all or nothing.',
        args: ['refs', 'status'],
        json: true,
      },
      { name: 'task assign', summary: 'Assign or unassign.', args: ['refs', 'who'], json: true },
      { name: 'task comment', summary: 'Append a comment.', args: ['ref', 'text'], json: true },
      { name: 'task edit', summary: 'Change fields.', args: ['refs'], json: true },
      { name: 'task log', summary: 'Log hours.', args: ['refs', 'hours'], json: true },
      { name: 'task block', summary: 'Record a blocker.', args: ['ref', 'blocker'], json: true },
      {
        name: 'decision add',
        summary: 'Record why something was chosen, and what was turned down.',
        args: ['title'],
        flags: ['--why', '--rejected', '--task', '--supersedes', '--doc'],
        json: true,
      },
      {
        name: 'decision list',
        summary: 'Current decisions. Superseded ones need --all.',
        flags: ['--all', '--task'],
        json: true,
      },
      { name: 'decision show', summary: 'One decision in full.', args: ['ref'], json: true },
      {
        name: 'task doc',
        summary: 'Link a document to a task. The file stays plain markdown in the repo.',
        args: ['ref', 'path'],
        json: true,
      },
      { name: 'sprint status', summary: 'Current sprint progress.', json: true },
      { name: 'sprint create', summary: 'Start a sprint.', args: ['name'], json: true },
      { name: 'sprint close', summary: 'Close it and report velocity.', json: true },
    ],
  };
}
